# pkg_reverse.py
#
# Author: Andrew Zimmer <andrew.zimmer@tigerbeetletechnology.com>
# SPDX-License-Identifier: MIT
"""Explode a flat .pkg into a working tree plus a blueprint (specs/pkg-reverse/).

The front end is bin/pkg-reverse.sh; its header is the usage text. Outputs, under
<dest>/<AppName>/: payload/, scripts/, blueprint.conf, bom.txt (lsbom -p mugsfl:
mode, uid, gid, size, path, link target, tab-separated) and, when ownership was not
preserved, chown-entries.txt (OWN<TAB><path><TAB><uid>:<gid>, parent first).

Exit codes: 0 done, 2 usage or input error, 3 multi-component distribution.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

from .pkg import (
    PkgError,
    chown_rollup,
    ditto,
    expand,
    lsbom,
    package_info,
    parse_lsbom,
    signature,
)


class UsageError(Exception):
    pass


def err(message: str = "") -> None:
    print(f"ERROR: {message}", file=sys.stderr)


def warn(message: str) -> None:
    print(f"WARN:  {message}", file=sys.stderr)


def section(title: str) -> None:
    print(f"=== {title} ===", flush=True)


def app_name_from(pkg: Path) -> str:
    """The folder name derived from a package file name (spec §1)."""
    name = pkg.name[:-4] if pkg.name.endswith(".pkg") else pkg.name
    name = name.replace(" ", "-").replace("_", "-")
    return re.sub(r"[^A-Za-z0-9-]", "", name)


def parse_args(argv: list[str]) -> dict:
    opts: dict = {"pkg": "", "dest": "", "name": "", "unpriv": False}
    args = list(argv)
    while args:
        arg = args.pop(0)
        if arg in ("--dest", "--name"):
            what = "a directory path" if arg == "--dest" else "a value"
            if not args or not args[0] or args[0].startswith("-"):
                raise UsageError(f"{arg} requires {what}")
            opts[arg[2:]] = args.pop(0)
        elif arg == "--allow-unprivileged":
            opts["unpriv"] = True
        elif arg in ("-h", "--help"):
            opts["help"] = True
            return opts
        elif arg.startswith("-"):
            raise UsageError(f"Unknown option: {arg}")
        elif opts["pkg"]:
            raise UsageError(f"Unexpected argument: {arg}")
        else:
            opts["pkg"] = arg
    if not opts["pkg"]:
        raise UsageError(
            "No package specified. Usage: pkg-reverse.sh <package.pkg> --dest <dir>"
        )
    if not opts["dest"]:
        raise UsageError(
            "--dest is required (the vendor_cache directory to write into)"
        )
    if not Path(opts["pkg"]).is_file():
        raise UsageError(f"Not a file: {opts['pkg']}")
    return opts


def privilege_check(unpriv: bool, argv: list[str]) -> bool:
    """True to continue. Prints the warnings or the refusal (spec §4)."""
    if os.geteuid() == 0:
        return True
    user, group = _names()
    if unpriv:
        warn(f"Running without root. Extracted files will be owned by {user}:{group},")
        warn(
            "not by what the package specifies. The blueprint will carry a chown block"
        )
        warn("so the recipe can restore ownership at build time.")
        return True
    for line in (
        "Not running as root.",
        "",
        "pkgutil extracts as the invoking user, so ownership from the original",
        "package would be lost and the rebuilt package would install files owned",
        "by you instead of by root (or whoever the package specifies).",
        "",
        f"Re-run as:  sudo pkg-reverse.sh {' '.join(argv)}",
        "Or pass --allow-unprivileged to proceed and reconstruct ownership from",
        "the BOM via a chown block in the generated recipe.",
    ):
        err(line)
    return False


def _names() -> tuple[str, str]:
    import grp
    import pwd

    try:
        user = pwd.getpwuid(os.getuid()).pw_name
    except KeyError:
        user = str(os.getuid())
    try:
        group = grp.getgrgid(os.getgid()).gr_name
    except KeyError:
        group = str(os.getgid())
    return user, group


def payload_stats(payload: Path) -> tuple[int, int, str]:
    files = dirs = 0
    for dirpath, _dirnames, filenames in os.walk(payload):
        dirs += 1
        files += sum(
            1 for f in filenames if not os.path.islink(os.path.join(dirpath, f))
        )
    done = subprocess.run(
        ["du", "-sh", str(payload)], capture_output=True, text=True, check=False
    )
    size = done.stdout.split("\t")[0].strip() if done.returncode == 0 else ""
    return files, dirs, size


def blueprint(fields: list[tuple[str, str]]) -> str:
    stamp = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    lines = [
        f"# blueprint.conf — generated by pkg-reverse.sh on {stamp}",
        "#",
        "# Input to blueprint-to-recipe.sh. Edit anything that is wrong BEFORE"
        " generating",
        "# the recipe — this file is meant to be reviewed, not trusted blindly.",
    ]
    groups = [
        ("app_name", "source_pkg", "source_pkg_basename"),
        ("pkg_kind", "component_count"),
        ("pkg_id", "version", "install_location"),
        ("signature_status", "signature_authority"),
        ("payload_files", "payload_dirs", "payload_size"),
        ("scripts",),
        ("ownership_preserved", "chown_block_needed"),
    ]
    values = dict(fields)
    for group in groups:
        lines.append("")
        lines.extend(f"{key}={values.get(key, '')}" for key in group)
    return "\n".join(lines) + "\n"


def reverse(opts: dict, argv: list[str]) -> int:
    pkg = Path(opts["pkg"]).resolve()
    name = opts["name"] or app_name_from(pkg)
    if not privilege_check(opts["unpriv"], argv):
        return 2
    as_root = os.geteuid() == 0

    out = Path(opts["dest"].rstrip("/") or "/") / name
    section(f"Reverse-engineering {name}")
    print(f"  source: {pkg}")
    print(f"  output: {out}")
    if out.exists() or out.is_symlink():
        err(
            f"Output already exists: {out}"
            " (remove it, or use --name for a different directory)"
        )
        return 2
    try:
        out.mkdir(parents=True)
    except OSError:
        err(f"Could not create {out}")
        return 2

    section("Expanding")
    expanded_dir = out / ".expanded"
    try:
        expanded = expand(pkg, expanded_dir)
    except PkgError as exc:
        err(str(exc))
        if "pkgutil" in str(exc):
            err(
                "  Is it actually a flat package?"
                " Bundle-style .pkg directories are not supported."
            )
        return 2

    count = len(expanded.components)
    if expanded.kind == "distribution" and count != 1:
        err(f"Distribution package with {count} components — not supported.")
        err()
        err("Components found:")
        for comp in expanded.components:
            print(f"    {comp.name}")
        err()
        err("A distribution package carries a Distribution XML with install choices,")
        err("requirements, and often JavaScript. PkgCreator cannot reproduce any of")
        err("that, so a generated recipe would silently drop it. Rebuild the")
        err("components individually, or keep this package and use PkgCopier.")
        err()
        err(f"Expanded tree left at {expanded_dir} for inspection.")
        return 3
    if expanded.kind == "distribution":
        warn(
            "Distribution wrapper around a single component"
            " — proceeding with that component."
        )
        warn("The Distribution XML's choices and requirements will NOT be reproduced.")
    comp = expanded.component
    print(f"  kind: {expanded.kind} ({count} component)")

    if not (comp / "PackageInfo").is_file():
        err(f"No PackageInfo in {comp}")
        return 2
    info = package_info(comp)
    section("Package metadata")
    print(f"  identifier:       {info['identifier'] or '<none>'}")
    print(f"  version:          {info['version'] or '<none>'}")
    print(f"  install-location: {info['install_location']}")

    section("Signature")
    sig_status, sig_authority = signature(pkg)
    if sig_status == "signed":
        print(f"  SIGNED by: {sig_authority}")
        warn("Rebuilding this package DISCARDS that signature.")
        warn("If you did not build this package yourself, prefer PkgCopier (Pattern 4")
        warn("Variant A) and ship the vendor's original.")
    else:
        print("  unsigned (expected for in-house packages)")

    section("Payload")
    payload_src = comp / "Payload"
    if not payload_src.is_dir():
        err(f"No expanded Payload directory at {payload_src}")
        return 2
    payload = out / "payload"
    try:
        ditto(payload_src, payload)
    except PkgError:
        err("ditto failed copying payload")
        return 2
    files, dirs, size = payload_stats(payload)
    print(f"  {files} files, {dirs} directories, {size}")

    section("Scripts")
    scripts_src = comp / "Scripts"
    script_list = ""
    if scripts_src.is_dir() and any(scripts_src.iterdir()):
        scripts = out / "scripts"
        try:
            ditto(scripts_src, scripts)
        except PkgError:
            err("ditto failed copying scripts")
            return 2
        # PkgCreator rejects a preinstall/postinstall that isn't executable.
        for script in ("preinstall", "postinstall"):
            path = scripts / script
            if path.is_file():
                path.chmod(path.stat().st_mode | 0o111)
        found = sorted(p for p in scripts.rglob("*") if p.is_file())
        for path in found:
            print(f"  {path.name}")
        script_list = "".join(f"{p.name} " for p in found)
    else:
        print("  none")

    section("BOM")
    bom_src = comp / "Bom"
    ownership_ok, chown_needed = "unknown", "false"
    entries = {}
    if bom_src.is_file():
        text = ""
        try:
            text = lsbom(bom_src)
        except PkgError:
            warn("lsbom failed; bom.txt may be incomplete")
        (out / "bom.txt").write_text(text)
        print(f"  {len(text.splitlines())} entries recorded in bom.txt")
        entries = parse_lsbom(text)
        if as_root:
            ownership_ok = "true"
            print("  ownership preserved (extracted as root)")
        else:
            ownership_ok, chown_needed = "false", "true"
            warn("ownership NOT preserved — recipe will need a chown block")
        uid = os.getuid()
        if entries and all(e.uid == uid for e in entries.values()):
            print(f"  note: BOM records all files as uid {uid} anyway")
    else:
        warn("No Bom file found — cannot verify ownership.")

    if chown_needed == "true" and (out / "bom.txt").is_file():
        section("Permission analysis")
        rollup = chown_rollup(entries)
        (out / "chown-entries.txt").write_text(
            "".join(f"OWN\t{path}\t{owner}\n" for path, owner in rollup)
        )
        print(
            f"  {len(rollup)} rolled-up ownership entries written to chown-entries.txt"
        )

    (out / "blueprint.conf").write_text(
        blueprint(
            [
                ("app_name", name),
                ("source_pkg", str(pkg)),
                ("source_pkg_basename", pkg.name),
                ("pkg_kind", expanded.kind),
                ("component_count", str(count)),
                ("pkg_id", info["identifier"]),
                ("version", info["version"]),
                ("install_location", info["install_location"]),
                ("signature_status", sig_status),
                ("signature_authority", sig_authority),
                ("payload_files", str(files)),
                ("payload_dirs", str(dirs)),
                ("payload_size", size),
                ("scripts", script_list),
                ("ownership_preserved", ownership_ok),
                ("chown_block_needed", chown_needed),
            ]
        )
    )
    shutil.rmtree(expanded_dir, ignore_errors=True)

    section("Done")
    print(f"  {out}/")
    print(f"    payload/         {files} files, {size}")
    print(f"    scripts/         {script_list or 'none'}")
    print("    blueprint.conf")
    print("    bom.txt")
    if chown_needed == "true":
        print("    chown-entries.txt")
    print("")
    print("  Review blueprint.conf, then:")
    print(
        "    bin/blueprint-to-recipe.sh --blueprint"
        f" {out}/blueprint.conf --out <recipe-dir>"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    try:
        opts = parse_args(argv)
    except UsageError as exc:
        err(str(exc))
        return 2
    if opts.get("help"):
        print(__doc__)
        return 0
    return reverse(opts, argv)


if __name__ == "__main__":
    # Warnings go to stderr between progress lines; keep them in order.
    sys.stdout.reconfigure(line_buffering=True)
    sys.exit(main())
